### ISSUE TITLE
Problem installing on Mac OS X Catalina

### ISSUE THREAD

**Issue by AntonPetrov** [pzhaojohnson/RNA2Drawer#2]
👋 Hello! 

I was trying to install RNA2Drawer by following the instructions in the Readme but ran into some problems because [Wine won't work on macOS Catalina 10.15](https://wiki.winehq.org/MacOS). Do you have any suggestions for how to run your software on the latest Mac OS X?

Any input will be appreciated! Thank you for looking into this.

**Comment by Jing-19** [comment]
Hi!
I have the same issue of downloading the "wine stable" on macOS Catalina, is there any other alternative software to help to run your software?

**Comment by pzhaojohnson** [comment]
Sorry for the late reply. (I thought I would have been notified when someone opens an issue.)

I don't know of another way to run RNA2Drawer on macOS without Wine. Fortunately, the second, web-based version of RNA2Drawer is starting to come to life. Right now it has basic features such as breaking and forming bonds, pivoting stems, and exporting a drawing in SVG or PPTX format. I think these features alone would make it useful to a lot of people, so we might make the second version available in the near future if only for Mac users to use.

**Comment by pzhaojohnson** [comment]
Here's a link to the second version: https://rna2drawer2.app

In the coming months more features of the first version will be added to it. Have fun!

**Comment by AntonPetrov** [comment]
The new web app looks great, thank you for sharing it! I will definitely use it.

A quick question: is the layout deterministic? For example, if 2 people run the same sequence independently, will the layout be the same? And what happens if the 2 sequences are slightly different - will the structures look similar? Thanks again!

**Comment by pzhaojohnson** [comment]
The characters of a sequence actually have no effect on the layout, only the secondary structure and other layout parameters (e.g. rotation and termini gap) control the layout. So, different sequences of the same length and with the same secondary structure and layout parameters will have the same layout.

**Comment by pzhaojohnson** [comment]
The RNA2Drawer [web app](https://rna2drawer.app) is now officially live and is available for Mac users.

**Comment by AntonPetrov** [comment]
Fantastic, thanks for the update! Closing the issue as the original problem has been fixed.
